version: '3'


services:
  php:
    build:
      context: .
    container_name: laravel
    volumes:
      - ./:/var/www/html
  web:
    image: nginx:1.17
    working_dir: /var/www/html
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - .docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf

