version: '3'


services:
  php:
    image: imagelaravel:latest
    volumes:
      - ./.env:/var/www/html/.env
   # environment:
    #  - APP_DEBUG="true"
     # - APP_KEY="base64:I/uGDqdQdgVbBGT6MPYcmCg9hiLYx57oWrvkU6ZaIE0="

 #   build:
  #    context: .
#
 #   volumes:
  #    - ./:/var/www/html


  web:
    #image: nginx:1.17
    #working_dir: /var/www/html
    image: imagenginx:latest
    ports:
      - "80:80"
    #volumes:
    #  - ./:/var/www/html
    #  - .docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf
